In [1]:
import tensorflow as tf

In [2]:
def reset_graph(seed=42):
    tf.reset_default_graph()
    tf.set_random_seed(seed)
    np.random.seed(seed)

In [3]:
print(tf.__version__)

1.14.0


In [4]:
import numpy as np
from sklearn.datasets import fetch_california_housing

reset_graph()

housing = fetch_california_housing()
m, n = housing.data.shape
housing_data_plus_bias = np.c_[np.ones((m,1)), housing.data]

X = tf.constant(housing_data_plus_bias, dtype = tf.float32, name="X")
y = tf.constant(housing.target.reshape(-1,1), dtype = tf.float32, name = "y")

XT = tf.transpose(X)
theta = tf.matmul(tf.matmul(tf.matrix_inverse(tf.matmul(XT,X)), XT), y)

In [5]:
with tf.Session() as sess:
  theta_val = theta.eval() 
  
print(theta_val)

[[-3.71799126e+01]
 [ 4.35986489e-01]
 [ 9.39679705e-03]
 [-1.06469184e-01]
 [ 6.41464353e-01]
 [-4.09536187e-06]
 [-3.77989258e-03]
 [-4.23745275e-01]
 [-4.37187374e-01]]


In [6]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_housing_data = scaler.fit_transform(housing.data)
scaled_housing_data_plus_bias = np.c_[np.ones((m,1)), scaled_housing_data]
scaled_housing_data_plus_bias

array([[ 1.        ,  2.34476576,  0.98214266, ..., -0.04959654,
         1.05254828, -1.32783522],
       [ 1.        ,  2.33223796, -0.60701891, ..., -0.09251223,
         1.04318455, -1.32284391],
       [ 1.        ,  1.7826994 ,  1.85618152, ..., -0.02584253,
         1.03850269, -1.33282653],
       ...,
       [ 1.        , -1.14259331, -0.92485123, ..., -0.0717345 ,
         1.77823747, -0.8237132 ],
       [ 1.        , -1.05458292, -0.84539315, ..., -0.09122515,
         1.77823747, -0.87362627],
       [ 1.        , -0.78012947, -1.00430931, ..., -0.04368215,
         1.75014627, -0.83369581]])

In [7]:
n_epochs = 1000
learning_rate = 0.01

reset_graph()

X = tf.constant(scaled_housing_data_plus_bias, dtype = tf.float32, name = "X")
y = tf.constant(housing.target.reshape(-1,1), dtype = tf.float32, name = "y")

theta = tf.Variable(tf.random_uniform([n+1, 1], -1.0, 1.0), name = "theta")
y_pred = tf.matmul(X, theta, name = "y_predictions")
error = y_pred - y
mse = tf.reduce_mean(tf.square(error), name = "mean_squared_error")
gradients = 2/m * tf.matmul(tf.transpose(X), error)
training_op = tf.assign(theta, theta - learning_rate*gradients)

init = tf.global_variables_initializer()

with tf.Session() as sess:
  sess.run(init)
  for epoch in range(n_epochs):
    if epoch%100 == 0:
      print(" epoch ",epoch," mse= ",mse.eval())
    sess.run(training_op)
  
  best_theta = theta.eval()
  
print(best_theta)

 epoch  0  mse=  12.408014
 epoch  100  mse=  0.75519687
 epoch  200  mse=  0.5420874
 epoch  300  mse=  0.5331699
 epoch  400  mse=  0.53053814
 epoch  500  mse=  0.5287963
 epoch  600  mse=  0.527549
 epoch  700  mse=  0.52664965
 epoch  800  mse=  0.5260011
 epoch  900  mse=  0.52553326
[[ 2.0685523e+00]
 [ 8.1063598e-01]
 [ 1.2685776e-01]
 [-2.0784086e-01]
 [ 2.4839850e-01]
 [-1.3083885e-03]
 [-3.9607048e-02]
 [-8.5861266e-01]
 [-8.2600272e-01]]


In [8]:
n_epochs = 1000
learning_rate = 0.01

reset_graph()

X = tf.constant(scaled_housing_data_plus_bias, dtype=tf.float32, name="X") 
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name="y") 
theta = tf.Variable(tf.random_uniform([n + 1, 1], -1.0, 1.0), name="theta") 
y_pred = tf.matmul(X, theta, name="predictions") 
error = y_pred - y 
mse = tf.reduce_mean(tf.square(error), name="mse")
gradients = tf.gradients(mse, [theta])[0]
training_op = tf.assign(theta, theta - learning_rate * gradients)
init = tf.global_variables_initializer()
with tf.Session() as sess: 
  sess.run(init)
  for epoch in range(n_epochs):
    if epoch % 100 == 0:  
      print("Epoch", epoch, "MSE =", mse.eval())    
    sess.run(training_op)
  best_theta = theta.eval() 
  
print(best_theta)

Epoch 0 MSE = 12.408014
Epoch 100 MSE = 0.75519687
Epoch 200 MSE = 0.5420874
Epoch 300 MSE = 0.53317
Epoch 400 MSE = 0.53053814
Epoch 500 MSE = 0.5287964
Epoch 600 MSE = 0.527549
Epoch 700 MSE = 0.5266497
Epoch 800 MSE = 0.5260011
Epoch 900 MSE = 0.5255332
[[ 2.0685525e+00]
 [ 8.1063598e-01]
 [ 1.2685777e-01]
 [-2.0784083e-01]
 [ 2.4839847e-01]
 [-1.3083883e-03]
 [-3.9607048e-02]
 [-8.5861266e-01]
 [-8.2600272e-01]]


In [9]:
n_epochs = 1000
learning_rate = 0.01

reset_graph()

X = tf.constant(scaled_housing_data_plus_bias, dtype=tf.float32, name="X") 
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name="y") 
theta = tf.Variable(tf.random_uniform([n + 1, 1], -1.0, 1.0), name="theta") 
y_pred = tf.matmul(X, theta, name="predictions") 
error = y_pred - y 
mse = tf.reduce_mean(tf.square(error), name="mse")

optimizer = tf.train.GradientDescentOptimizer(learning_rate = learning_rate)
training_op = optimizer.minimize(mse)

init = tf.global_variables_initializer()
with tf.Session() as sess: 
  sess.run(init)
  for epoch in range(n_epochs):
    if epoch % 100 == 0:  
      print("Epoch", epoch, "MSE =", mse.eval())    
    sess.run(training_op)
  best_theta = theta.eval() 
  
print(best_theta)

Epoch 0 MSE = 12.408014
Epoch 100 MSE = 0.75519687
Epoch 200 MSE = 0.5420874
Epoch 300 MSE = 0.53317
Epoch 400 MSE = 0.53053814
Epoch 500 MSE = 0.5287964
Epoch 600 MSE = 0.527549
Epoch 700 MSE = 0.5266497
Epoch 800 MSE = 0.5260011
Epoch 900 MSE = 0.5255332
[[ 2.0685525e+00]
 [ 8.1063598e-01]
 [ 1.2685777e-01]
 [-2.0784083e-01]
 [ 2.4839847e-01]
 [-1.3083883e-03]
 [-3.9607048e-02]
 [-8.5861266e-01]
 [-8.2600272e-01]]


In [11]:
n_epochs = 10
learning_rate = 0.01

reset_graph()

X = tf.placeholder(tf.float32, shape=(None, n + 1), name="X")
y = tf.placeholder(tf.float32, shape=(None, 1), name="y")

theta = tf.Variable(tf.random_uniform([n + 1, 1], -1.0, 1.0, seed=42), name="theta")
y_pred = tf.matmul(X, theta, name="predictions")
error = y_pred - y
mse = tf.reduce_mean(tf.square(error), name="mse")
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate)
training_op = optimizer.minimize(mse)

init = tf.global_variables_initializer()

batch_size = 100
n_batches = int(np.ceil(m / batch_size))

def fetch_data(epoch, batch_index, batch_size):
  np.random.seed(42)
  indices = np.random.randint(m, size = batch_size)
  X_batch = scaled_housing_data_plus_bias[indices]
  y_batch = housing.target.reshape(-1,1)[indices]
  return X_batch, y_batch
   
with tf.Session() as sess:
  sess.run(init)
  for epoch in range(n_epochs):
    for batch_index in range(n_batches):
      X_batch, y_batch = fetch_data(epoch, batch_index, batch_size)
      sess.run(training_op, feed_dict = {X:X_batch, y:y_batch})
  best_theta = theta.eval()

best_theta

array([[ 2.0877347 ],
       [ 0.81425226],
       [-0.0394018 ],
       [-0.42498362],
       [ 0.30571643],
       [-0.08363095],
       [-0.3432868 ],
       [-1.0353643 ],
       [-0.95280176]], dtype=float32)

In [12]:
reset_graph()

n_epochs = 1000                                                                       # not shown in the book
learning_rate = 0.01                                                                  # not shown

X = tf.constant(scaled_housing_data_plus_bias, dtype=tf.float32, name="X")            # not shown
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name="y")            # not shown
theta = tf.Variable(tf.random_uniform([n + 1, 1], -1.0, 1.0, seed=42), name="theta")
y_pred = tf.matmul(X, theta, name="predictions")                                      # not shown
error = y_pred - y                                                                    # not shown
mse = tf.reduce_mean(tf.square(error), name="mse")                                    # not shown
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate)            # not shown
training_op = optimizer.minimize(mse)                                                 # not shown

init = tf.global_variables_initializer()
saver = tf.train.Saver()

with tf.Session() as sess:
    sess.run(init)

    for epoch in range(n_epochs):
        if epoch % 100 == 0:
            print("Epoch", epoch, "MSE =", mse.eval())                                # not shown
            save_path = saver.save(sess, "/tmp/my_model.ckpt")
        sess.run(training_op)
    
    best_theta = theta.eval()
    save_path = saver.save(sess, "/tmp/my_model_final.ckpt")

Epoch 0 MSE = 9.161542
Epoch 100 MSE = 0.7145004
Epoch 200 MSE = 0.56670487
Epoch 300 MSE = 0.55557173
Epoch 400 MSE = 0.5488112
Epoch 500 MSE = 0.5436363
Epoch 600 MSE = 0.53962904
Epoch 700 MSE = 0.5365092
Epoch 800 MSE = 0.53406775
Epoch 900 MSE = 0.5321473


In [13]:
with tf.Session() as sess:
    saver.restore(sess, "/tmp/my_model_final.ckpt")
    best_theta_restored = theta.eval() # not shown in the book

Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from /tmp/my_model_final.ckpt


In [14]:
best_theta_restored

array([[ 2.0685525 ],
       [ 0.8874027 ],
       [ 0.14401658],
       [-0.34770882],
       [ 0.36178368],
       [ 0.00393811],
       [-0.04269556],
       [-0.6614528 ],
       [-0.6375277 ]], dtype=float32)

In [19]:
reset_graph()

from datetime import datetime

now = datetime.utcnow().strftime("%Y%m%d%H%M%S")
root_logdir = "tf_logs"
logdir = "{}/run-{}/".format(root_logdir, now)

In [20]:
n_epochs = 1000
learning_rate = 0.01

X = tf.placeholder(tf.float32, shape=(None, n + 1), name="X")
y = tf.placeholder(tf.float32, shape=(None, 1), name="y")
theta = tf.Variable(tf.random_uniform([n + 1, 1], -1.0, 1.0, seed=42), name="theta")
y_pred = tf.matmul(X, theta, name="predictions")
error = y_pred - y
mse = tf.reduce_mean(tf.square(error), name="mse")
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate)
training_op = optimizer.minimize(mse)

init = tf.global_variables_initializer()

In [21]:
mse_summary = tf.summary.scalar('MSE', mse)
file_writer = tf.summary.FileWriter(logdir, tf.get_default_graph())

In [22]:
from datetime import datetime

now = datetime.utcnow().strftime("%Y%m%d%H%M%S")
root_logdir = 'tf_logs'
logdir = '{}/run-{}/'.format(root_logdir, now)

n_epochs = 1000
learning_rate = 0.01

X = tf.placeholder(tf.float32, shape=(None, n + 1), name="X")
y = tf.placeholder(tf.float32, shape=(None, 1), name="y")
theta = tf.Variable(tf.random_uniform([n + 1, 1], -1.0, 1.0, seed=42), name="theta")
y_pred = tf.matmul(X, theta, name="predictions")
error = y_pred - y
mse = tf.reduce_mean(tf.square(error), name="mse")
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate)
training_op = optimizer.minimize(mse)

init = tf.global_variables_initializer()

mse_summary = tf.summary.scalar('MSE', mse)
file_writer = tf.summary.FileWriter(logdir, tf.get_default_graph())

with tf.Session() as sess: 
  sess.run(init)
  for epoch in range(n_epochs):
    for batch_index in range(n_batches):
      X_batch, y_batch = fetch_data(epoch, batch_index, batch_size)
      if batch_index%10 == 0:
          summary_str = mse_summary.eval(feed_dict={X:X_batch, y:y_batch})
          step = epoch*n_batches + batch_index
          file_writer.add_summary(summary_str, step)
      sess.run(training_op, feed_dict = {X:X_batch, y:y_batch})
  best_theta = theta.eval()

In [23]:
best_theta

array([[ 2.0685525 ],
       [ 0.8874027 ],
       [ 0.14401658],
       [-0.34770882],
       [ 0.36178368],
       [ 0.00393811],
       [-0.04269556],
       [-0.6614528 ],
       [-0.6375277 ]], dtype=float32)

In [24]:
file_writer.close()

In [26]:
n_features = 3
X = tf.placeholder(tf.float32, shape = (None, n_features), name = 'X')

w1  = tf.Variable(tf.random_normal((n_features, 1)), name = 'weight1')
w2 = tf.Variable(tf.random_normal((n_features, 1)), name = 'weight2')
b1 = tf.Variable(0.0, name = 'bias1')
b2 = tf.Variable(0.0, name = 'bias2')

z1 = tf.add(tf.matmul(X,w1), b1, name = 'z1')
z2 = tf.add(tf.matmul(X,w2), b2, name = 'z2')

relu1 = tf.maximum(z1, 0.0, name = "relu1")
relu2 = tf.maximum(z2, 0.0, name = 'relu2')

output = tf.add(relu1, relu2, name = 'output')
print(output)

Tensor("output:0", shape=(?, 1), dtype=float32)


In [34]:
reset_graph()

def relu(X):
  with tf.variable_scope('relu',reuse=True):
    threshold = tf.get_variable('threshold')
    m = int(X.get_shape()[1])
    w = tf.Variable(tf.random_normal((m, 1)), name = "weights")
    b = tf.Variable(0.0, name = 'biases')
    z = tf.add(tf.matmul(X, w), b, name = 'z')
    return tf.maximum(z, threshold, name='relu') 

n_features = 3

with tf.variable_scope('relu'):
    threshold = tf.get_variable('threshold', shape=(), initializer = tf.constant_initializer(0.0))

X = tf.placeholder(tf.float32, shape=(None, n_features), name='X')
relus = [relu(X) for i in range(5) ]
output = tf.add_n(relus, name='output')

file_writer = tf.summary.FileWriter('logs/relu3', tf.get_default_graph())
file_writer.close()

In [36]:
reset_graph()

def relu(X):
    with tf.variable_scope("relu"):
        threshold = tf.get_variable("threshold", shape=(), initializer=tf.constant_initializer(0.0))
        w_shape = (int(X.get_shape()[1]), 1)
        w = tf.Variable(tf.random_normal(w_shape), name="weights")
        b = tf.Variable(0.0, name="bias")
        z = tf.add(tf.matmul(X, w), b, name="z")
        return tf.maximum(z, threshold, name="max")

relus = []
X = tf.placeholder(tf.float32, shape=(None, n_features), name="X")
for relu_index in range(5): 
    with tf.variable_scope("relu", reuse=(relu_index >= 1)) as scope:
        relus.append(relu(X))
output = tf.add_n(relus, name="output")

file_writer = tf.summary.FileWriter("logs/relu8", tf.get_default_graph())
file_writer.close()