In [0]:
import tensorflow as tf

x = tf.Variable(3, name='x')
y = tf.Variable(4, name='y')
f = x*x*y + y + 2

In [2]:
sess = tf.Session()
sess.run(x.initializer)
sess.run(y.initializer)
result = sess.run(f)
print(result)

42


In [3]:
print(tf.__version__)

1.14.0


In [4]:
with tf.Session() as sess:
  x.initializer.run()
  y.initializer.run()
  result = f.eval()
  
print(result)

42


In [5]:
init = tf.global_variables_initializer()

with tf.Session() as sess:
  init.run()
  result = f.eval()
print(result)

42


In [6]:
init = tf.global_variables_initializer()
sess = tf.InteractiveSession()

init.run()
result = f.eval()
print(result)

sess.close()

42


In [7]:
x1 = tf.Variable(1)
x1.graph is tf.get_default_graph()

True

In [8]:
graph = tf.Graph()

with graph.as_default():
  x2 = tf.Variable(2)
  
x2.graph is graph 

True

In [9]:
x2.graph is tf.get_default_graph()

False

In [0]:
w = tf.constant(3)
x = w+2
y=x+5
z=x*3

In [11]:
with tf.Session() as sess:
  print(y.eval())
  print(z.eval())

10
15


In [12]:
with tf.Session() as sess:
  y_val, z_val = sess.run([y, z])
  print(y_val)
  print(z_val)

10
15


In [13]:
import numpy as np
from sklearn.datasets import fetch_california_housing

housing = fetch_california_housing()
m, n = housing.data.shape
housing_data_plus_bias = np.c_[np.ones((m,1)), housing.data]

X = tf.constant(housing_data_plus_bias, dtype = tf.float32, name="X")
y = tf.constant(housing.target.reshape(-1,1), dtype = tf.float32, name = "y")

XT = tf.transpose(X)
theta = tf.matmul(tf.matmul(tf.matrix_inverse(tf.matmul(XT,X)), XT), y)

In [14]:
with tf.Session() as sess:
  theta_val = theta.eval() 
  
print(theta_val)

[[-3.67372932e+01]
 [ 4.37366009e-01]
 [ 9.47520509e-03]
 [-1.08159676e-01]
 [ 6.48537397e-01]
 [-3.84734449e-06]
 [-3.79239232e-03]
 [-4.19136107e-01]
 [-4.32144403e-01]]


In [15]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_housing_data = scaler.fit_transform(housing.data)
scaled_housing_data_plus_bias = np.c_[np.ones((m,1)), scaled_housing_data]
scaled_housing_data_plus_bias

array([[ 1.        ,  2.34476576,  0.98214266, ..., -0.04959654,
         1.05254828, -1.32783522],
       [ 1.        ,  2.33223796, -0.60701891, ..., -0.09251223,
         1.04318455, -1.32284391],
       [ 1.        ,  1.7826994 ,  1.85618152, ..., -0.02584253,
         1.03850269, -1.33282653],
       ...,
       [ 1.        , -1.14259331, -0.92485123, ..., -0.0717345 ,
         1.77823747, -0.8237132 ],
       [ 1.        , -1.05458292, -0.84539315, ..., -0.09122515,
         1.77823747, -0.87362627],
       [ 1.        , -0.78012947, -1.00430931, ..., -0.04368215,
         1.75014627, -0.83369581]])

In [16]:


n_epochs = 1000
learning_rate = 0.01

X = tf.constant(scaled_housing_data_plus_bias, dtype = tf.float32, name = "X")
y = tf.constant(housing.target.reshape(-1,1), dtype = tf.float32, name = "y")

theta = tf.Variable(tf.random_uniform([n+1, 1], -1.0, 1.0), name = "theta")
y_pred = tf.matmul(X, theta, name = "y_predictions")
error = y_pred - y
mse = tf.reduce_mean(tf.square(error), name = "mean_squared_error")
gradients = 2/m * tf.matmul(tf.transpose(X), error)
training_op = tf.assign(theta, theta - learning_rate*gradients)

init = tf.global_variables_initializer()

with tf.Session() as sess:
  sess.run(init)
  for epoch in range(n_epochs):
    if epoch%100 == 0:
      print(" epoch ",epoch," mse= ",mse.eval())
    sess.run(training_op)
  
  best_theta = theta.eval()
  
print(best_theta)

"""
n_epochs = 1000
learning_rate = 0.01


X = tf.constant(scaled_housing_data_plus_bias, dtype = tf.float32, name="X") 
y = tf.constant(housing.target.reshape(-1,1), dtype = tf.float32, name="y") 
theta = tf.Variable(tf.random_uniform([n+1, 1], -1.0, 1.0), name="theta") 
y_pred = tf.matmul(X, theta, name="predictions") 
error = y_pred - y 
mse = tf.reduce_mean(tf.square(error), name="mse")
gradients = 2/m * tf.matmul(tf.transpose(X), error)
training_op = tf.assign(theta, theta - learning_rate*gradients)
init = tf.global_variables_initializer()
with tf.Session() as sess: 
  sess.run(init)
  for epoch in range(n_epochs):
    if epoch%100 == 0:  
      print("Epoch", epoch, "MSE =", mse.eval())    
    sess.run(training_op)
  best_theta = theta.eval() """

 epoch  0  mse=  10.048654
 epoch  100  mse=  0.8211299
 epoch  200  mse=  0.6296893
 epoch  300  mse=  0.60049677
 epoch  400  mse=  0.5810024
 epoch  500  mse=  0.56667984
 epoch  600  mse=  0.5561035
 epoch  700  mse=  0.54826975
 epoch  800  mse=  0.54244846
 epoch  900  mse=  0.5381073
[[ 2.0685523e+00]
 [ 7.0790410e-01]
 [ 1.2701428e-01]
 [ 2.2572313e-02]
 [ 4.1895822e-02]
 [ 8.2776292e-05]
 [-3.7430048e-02]
 [-9.5394969e-01]
 [-9.0762639e-01]]


'\nn_epochs = 1000\nlearning_rate = 0.01\n\n\nX = tf.constant(scaled_housing_data_plus_bias, dtype = tf.float32, name="X") \ny = tf.constant(housing.target.reshape(-1,1), dtype = tf.float32, name="y") \ntheta = tf.Variable(tf.random_uniform([n+1, 1], -1.0, 1.0), name="theta") \ny_pred = tf.matmul(X, theta, name="predictions") \nerror = y_pred - y \nmse = tf.reduce_mean(tf.square(error), name="mse")\ngradients = 2/m * tf.matmul(tf.transpose(X), error)\ntraining_op = tf.assign(theta, theta - learning_rate*gradients)\ninit = tf.global_variables_initializer()\nwith tf.Session() as sess: \n  sess.run(init)\n  for epoch in range(n_epochs):\n    if epoch%100 == 0:  \n      print("Epoch", epoch, "MSE =", mse.eval())    \n    sess.run(training_op)\n  best_theta = theta.eval() '

In [17]:
n_epochs = 1000
learning_rate = 0.01

X = tf.constant(scaled_housing_data_plus_bias, dtype=tf.float32, name="X") 
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name="y") 
theta = tf.Variable(tf.random_uniform([n + 1, 1], -1.0, 1.0), name="theta") 
y_pred = tf.matmul(X, theta, name="predictions") 
error = y_pred - y 
mse = tf.reduce_mean(tf.square(error), name="mse")
gradients = tf.gradients(mse, [theta])[0]
training_op = tf.assign(theta, theta - learning_rate * gradients)
init = tf.global_variables_initializer()
with tf.Session() as sess: 
  sess.run(init)
  for epoch in range(n_epochs):
    if epoch % 100 == 0:  
      print("Epoch", epoch, "MSE =", mse.eval())    
    sess.run(training_op)
  best_theta = theta.eval() 
  
print(best_theta)

Epoch 0 MSE = 4.3552947
Epoch 100 MSE = 0.87964815
Epoch 200 MSE = 0.7447146
Epoch 300 MSE = 0.68268
Epoch 400 MSE = 0.6389591
Epoch 500 MSE = 0.6074014
Epoch 600 MSE = 0.58457625
Epoch 700 MSE = 0.5680576
Epoch 800 MSE = 0.5560968
Epoch 900 MSE = 0.5474313
[[ 2.0685525 ]
 [ 0.7944369 ]
 [ 0.16144656]
 [-0.10686116]
 [ 0.13394842]
 [ 0.01148501]
 [-0.04218767]
 [-0.6216856 ]
 [-0.58378595]]


In [18]:
n_epochs = 1000
learning_rate = 0.01

X = tf.constant(scaled_housing_data_plus_bias, dtype=tf.float32, name="X") 
y = tf.constant(housing.target.reshape(-1, 1), dtype=tf.float32, name="y") 
theta = tf.Variable(tf.random_uniform([n + 1, 1], -1.0, 1.0), name="theta") 
y_pred = tf.matmul(X, theta, name="predictions") 
error = y_pred - y 
mse = tf.reduce_mean(tf.square(error), name="mse")

optimizer = tf.train.GradientDescentOptimizer(learning_rate = learning_rate)
training_op = optimizer.minimize(mse)

init = tf.global_variables_initializer()
with tf.Session() as sess: 
  sess.run(init)
  for epoch in range(n_epochs):
    if epoch % 100 == 0:  
      print("Epoch", epoch, "MSE =", mse.eval())    
    sess.run(training_op)
  best_theta = theta.eval() 
  
print(best_theta)

Epoch 0 MSE = 5.3112473
Epoch 100 MSE = 0.71815103
Epoch 200 MSE = 0.6289818
Epoch 300 MSE = 0.59976006
Epoch 400 MSE = 0.5794703
Epoch 500 MSE = 0.56474596
Epoch 600 MSE = 0.55401963
Epoch 700 MSE = 0.5461927
Epoch 800 MSE = 0.5404721
Epoch 900 MSE = 0.5362832
[[ 2.0685525 ]
 [ 0.8301478 ]
 [ 0.15164764]
 [-0.20518379]
 [ 0.2288214 ]
 [ 0.00745759]
 [-0.04212039]
 [-0.65959156]
 [-0.627341  ]]


In [22]:
a = tf.placeholder(tf.float32, shape=(None,3))
b = a + 5
with tf.Session() as sess:
  b_1 = b.eval(feed_dict = {a:[[1,2,3]]})
  b_2 = b.eval(feed_dict = {a:[[1,2,3],[4,5,6]]})
  
print(b_1,'\n',b_2)

[[6. 7. 8.]] 
 [[ 6.  7.  8.]
 [ 9. 10. 11.]]


In [0]:
X = tf.placeholder(tf.float32, shape=(None, n+1), name = 'X')
y = tf.placeholder(tf.float32, shape=(None, 1), name = 'y')

batch_size = 100
n_batches = np.ceil(m/batch_size)

def fetch_data(epoch, batch_index, batch_size):
  if batch_size*(batch_index + 1) <= m :
    X_batch = scaled_housing_data_plus_bias[ batch_index*batch_size: (batch_index+1)*batch_size , : ]
    y_batch = housing.target[ batch_index*batch_size: (batch_index+1)*batch_size , 1 ].reshape(-1,1)
  else:
    X_batch = scaled_housing_data_plus_bias[ batch_index*batch_size: m , : ]
    y_batch = housing.target[ batch_index*batch_size: m , 1 ].reshape(-1,1)
  
return X_batch, y_batch
   
with tf.Session() as sess:
  sess.run(init)
  for epoch in range(n_epochs):
    for batch_index in range(n_batches):
      X_batch, y_batch = fetch_data(epoch, batch_index, batch_size)
      sess.run(training_op, feed_dict = {X:X_batch, y:y_batch})
  best_theta = theta.eval()

In [0]:
a=[1,2,3,4,5]
b = a[:,:]