In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn import datasets
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC

In [2]:
iris = datasets.load_iris()

In [3]:
X = iris['data'][:,(2,3)]
y = ( iris['target'] == 2 ).astype(np.float64)

In [4]:
svm_clf = Pipeline((
    ('scaler', StandardScaler()),
    ('lin_svc', LinearSVC(C=1, loss='hinge'))
))
svm_clf.fit(X,y)
svm_clf.predict([[5.5, 1.7]])

array([1.])

In [36]:
from sklearn.datasets import make_moons
from sklearn.preprocessing import PolynomialFeatures
make_moons
X, y = datasets.make_moons(n_samples = 300, shuffle = True, noise = 0.05, random_state = 42)
X, y

(array([[ 6.22519125e-01, -3.72101344e-01],
        [ 1.90426932e+00, -1.36302945e-01],
        [-6.94312816e-02,  4.56116985e-01],
        [ 9.33898633e-01,  2.37482827e-01],
        [ 1.18035952e+00, -4.90846917e-01],
        [ 1.02541488e+00, -4.62482874e-01],
        [ 4.11984697e-01, -2.85969715e-01],
        [-6.12663134e-01,  7.29788185e-01],
        [ 9.48145854e-01,  7.95791386e-02],
        [ 1.71242445e-01,  1.58374951e-03],
        [ 1.29201956e+00, -3.77322706e-01],
        [ 3.72211026e-01,  8.92249223e-01],
        [ 9.16250451e-01, -4.88055386e-01],
        [ 6.26278567e-01,  8.66028662e-01],
        [ 1.71157998e-01, -5.55663311e-02],
        [ 9.71527259e-01, -5.27473544e-01],
        [ 1.99307684e+00,  3.03573972e-01],
        [ 7.20383729e-01, -4.16166842e-01],
        [-9.27909913e-01,  2.14482709e-02],
        [ 1.16141211e-01,  2.38388568e-01],
        [-6.21140311e-02,  1.00608737e+00],
        [-7.83123575e-01,  6.13188694e-01],
        [ 1.50215227e+00, -4.123

In [37]:
from sklearn.svm import LinearSVC

poly_svm_clf = Pipeline((
    ('poly_feat', PolynomialFeatures(degree = 3)),
    ('scaler', StandardScaler()),
    ('svm_clf', LinearSVC(C = 10, loss = 'hinge'))
))
poly_svm_clf.fit(X,y)
poly_svm_clf.predict([[-5.06952598e-01,  8.43251391e-01]])

C:\Users\rajar\Anaconda3\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


array([0], dtype=int64)

In [38]:
from sklearn.svm import SVC

poly_kernel_svm_clf = Pipeline((
    ('scaler', StandardScaler()),
    ('svc_clf', SVC(kernel='poly', degree = 3, coef0 = 1, C = 5 ))
))
poly_kernel_svm_clf.fit(X, y)
poly_kernel_svm_clf.predict([[6.22519125e-01, -3.72101344e-01]])

array([1], dtype=int64)

In [39]:
from sklearn.svm import SVC

rbf_kernel_svm_clf = Pipeline((
    ('scaler', StandardScaler()),
    ('svm_clf', SVC(kernel = 'rbf', gamma = 5, C = 0.001))
))
rbf_kernel_svm_clf.fit(X, y)
rbf_kernel_svm_clf.predict([[6.22519125e-01, -3.72101344e-01]])

array([1], dtype=int64)

In [56]:
np.random.seed(42)
X = np.random.randn(100,1)
y = 4 + 3*X + np.random.randn(100,1)
print(f'{X}\n\n\n\n')
print(y)

[[ 0.49671415]
 [-0.1382643 ]
 [ 0.64768854]
 [ 1.52302986]
 [-0.23415337]
 [-0.23413696]
 [ 1.57921282]
 [ 0.76743473]
 [-0.46947439]
 [ 0.54256004]
 [-0.46341769]
 [-0.46572975]
 [ 0.24196227]
 [-1.91328024]
 [-1.72491783]
 [-0.56228753]
 [-1.01283112]
 [ 0.31424733]
 [-0.90802408]
 [-1.4123037 ]
 [ 1.46564877]
 [-0.2257763 ]
 [ 0.0675282 ]
 [-1.42474819]
 [-0.54438272]
 [ 0.11092259]
 [-1.15099358]
 [ 0.37569802]
 [-0.60063869]
 [-0.29169375]
 [-0.60170661]
 [ 1.85227818]
 [-0.01349722]
 [-1.05771093]
 [ 0.82254491]
 [-1.22084365]
 [ 0.2088636 ]
 [-1.95967012]
 [-1.32818605]
 [ 0.19686124]
 [ 0.73846658]
 [ 0.17136828]
 [-0.11564828]
 [-0.3011037 ]
 [-1.47852199]
 [-0.71984421]
 [-0.46063877]
 [ 1.05712223]
 [ 0.34361829]
 [-1.76304016]
 [ 0.32408397]
 [-0.38508228]
 [-0.676922  ]
 [ 0.61167629]
 [ 1.03099952]
 [ 0.93128012]
 [-0.83921752]
 [-0.30921238]
 [ 0.33126343]
 [ 0.97554513]
 [-0.47917424]
 [-0.18565898]
 [-1.10633497]
 [-1.19620662]
 [ 0.81252582]
 [ 1.35624003]
 [-0.07201

In [57]:
from sklearn.svm import LinearSVR

lin_svm_reg = Pipeline((
    ('scaler', StandardScaler()),
    ('lin_reg', LinearSVR(epsilon = 1.5))
))

In [59]:
lin_svm_reg.fit(X,y)
lin_svm_reg.predict([[0.49671415]])

C:\Users\rajar\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([5.20527869])

In [62]:
from sklearn.svm import SVR

poly_svm_reg = Pipeline((
    ('scaler', StandardScaler()),
    ('svm_reg', SVR(kernel = 'poly', degree= 3, C=100, epsilon = 0.1))
))
poly_svm_reg.fit(X,y)
poly_svm_reg.predict([[0.49671415]])

C:\Users\rajar\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([3.93899589])